/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACollapse: typeof import('ant-design-vue')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue')['CollapsePanel']
    AConfigProvider: typeof import('ant-design-vue')['ConfigProvider']
  }
}
